name: config of answer generation for m-arena-hard-el

bench_name: m-arena-hard-el

temperature: 0.0
max_tokens: 8192
num_choices: 1

# a list of model to generate answers
model_list:
  - Qwen2.5-14B-Instruct
